---
- name: 'Set initial variables'
  set_fact:
    packer_builder_list: []
    packer_provisioners: '{{ packer_options.get("provisioners", []) }}'
    packer_post_processors: '{{ packer_options.get("post-processors", []) }}'
    packer_variables: {}
    packer_sensitive_variables: '{{ packer_options.get("sensitive-variables", []) }}'

- name: 'Convert builders from dictionary to list'
  set_fact:
    packer_builder_list: '{{ packer_builder_list + [builder] }}'
  vars:
    builder: '{{ {"name": item.key } | combine(item.value or {}, {"type": (item.value or {}).get("type", item.key) }) }}'
  with_dict: '{{ packer_options.builders }}'

- name: 'Execute pre-configured image tasks'
  when: 'packer_image is defined'
  include_tasks: 'preconfigured.yml'

- name: 'Convert variables to string'
  set_fact:
    packer_variables: '{{ packer_variables | combine({ item.key: item.value|string}) }}'
  no_log: true
  with_dict: '{{ packer_options.get("variables", {}) }}'

- name: 'Generate packer template'
  copy:
    content: "{{ packer_template | to_nice_json | string | replace('[[', '{{') | replace(']]', '}}') | string }}"
    dest: '{{ packer_template_path }}'
  vars:
    packer_template:
      builders: '{{ packer_builder_list }}'
      provisioners: '{{ packer_provisioners }}'
      post-processors: '{{ packer_post_processors }}'
      variables: '{{ packer_variables }}'
      sensitive-variables: '{{ packer_sensitive_variables }}'
