---
scenario:
  name: default
provisioner:
  name: ansible
  lint:
    name: ansible-lint
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu:bionic
verifier:
  name: testinfra
  lint:
    name: flake8
