---
- name: Converge
  hosts: all
  pre_tasks:
    - name: 'Create destination directory'
      file:
        state: 'directory'
        path: '/tmp/packer'
  roles:
    - role: packer-template
      packer_name: 'CustomBuild'
      packer_dest: '/tmp/packer'
      packer_options:
        builders:
          virtualbox-iso:
            iso_url: 'http://example.com/example.iso'
            iso_checksum_type: 'none'
            ssh_username: 'root'

    - role: packer-template
      packer_name: 'PackageBuild'
      packer_dest: '/tmp/packer'
      packer_package: 'sample_package'
      packer_options:
        builders:
          virtualbox-iso:
